dist: trusty
sudo: false
language: python
python:
  - 2.7
  - 3.5
  - 3.6
env:
  - DJANGO_VERSION=1.8.18
  - DJANGO_VERSION=1.9.13
  - DJANGO_VERSION=1.10.7
  - DJANGO_VERSION=1.11.1
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r test_requirements.txt
script: coverage run --source='balancer' runtests.py
notifications:
  email: false
after_success:
  - coveralls
